-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.activity_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  action character varying NOT NULL,
  data jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT activity_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bookings_kereta (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  schedule_id uuid DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  booking_code character varying NOT NULL UNIQUE,
  total_amount numeric NOT NULL CHECK (total_amount >= 0::numeric),
  status character varying,
  booking_date timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  passenger_count integer DEFAULT 1,
  payment_status character varying,
  payment_method character varying,
  order_id character varying,
  arrival_time time without time zone,
  train_type character varying,
  origin character varying,
  destination character varying,
  departure_date date,
  departure_time time without time zone,
  passenger_name character varying,
  passenger_email character varying,
  passenger_phone character varying,
  passenger_details text,
  train_code character varying,
  train_name character varying,
  payment_date timestamp without time zone,
  transit_route_id uuid,
  transit_details jsonb,
  transit_segments jsonb DEFAULT '[]'::jsonb,
  transit_stations jsonb DEFAULT '[]'::jsonb,
  transit_total_adjustment numeric DEFAULT 0,
  transit_discount numeric DEFAULT 0,
  customer_email text,
  transit_arrival time without time zone,
  transit_departure time without time zone,
  transit_station character varying,
  admin_fee numeric DEFAULT 5000,
  insurance_fee numeric DEFAULT 10000,
  seat_premium numeric DEFAULT 0,
  base_price numeric DEFAULT 265000,
  promo_discount numeric DEFAULT 0,
  CONSTRAINT bookings_kereta_pkey PRIMARY KEY (id),
  CONSTRAINT bookings_kereta_schedule_id_fkey FOREIGN KEY (schedule_id) REFERENCES public.jadwal_kereta(id),
  CONSTRAINT bookings_kereta_transit_route_id_fkey FOREIGN KEY (transit_route_id) REFERENCES public.transit_routes(id)
);
CREATE TABLE public.detail_pemesanan (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  id_jadwal uuid,
  pemesanan_id uuid,
  nama_penumpang character varying NOT NULL,
  kode_kereta character varying,
  seat_id uuid,
  status character varying DEFAULT 'confirmed'::character varying,
  harga numeric NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT detail_pemesanan_pkey PRIMARY KEY (id),
  CONSTRAINT detail_pemesanan_pemesanan_id_fkey FOREIGN KEY (pemesanan_id) REFERENCES public.pemesanan(id),
  CONSTRAINT detail_pemesanan_seat_id_fkey FOREIGN KEY (seat_id) REFERENCES public.seat(id)
);
CREATE TABLE public.gerbong (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  train_id uuid,
  coach_code character varying NOT NULL,
  class_type USER-DEFINED NOT NULL,
  total_seats integer NOT NULL CHECK (total_seats > 0),
  layout jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT gerbong_pkey PRIMARY KEY (id),
  CONSTRAINT gerbong_train_id_fkey FOREIGN KEY (train_id) REFERENCES public.kereta(id)
);
CREATE TABLE public.jadwal_kereta (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  train_id uuid,
  travel_date date NOT NULL,
  status USER-DEFINED DEFAULT 'scheduled'::status_enum,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT jadwal_kereta_pkey PRIMARY KEY (id),
  CONSTRAINT jadwal_kereta_train_id_fkey FOREIGN KEY (train_id) REFERENCES public.kereta(id)
);
CREATE TABLE public.kelas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nama_kelas character varying NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT kelas_pkey PRIMARY KEY (id)
);
CREATE TABLE public.kereta (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  kode_kereta character varying NOT NULL UNIQUE,
  nama_kereta character varying NOT NULL,
  operator character varying NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  tipe_kereta character varying,
  jumlah_kursi integer,
  fasilitas jsonb DEFAULT '{}'::jsonb,
  keterangan text,
  CONSTRAINT kereta_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['booking'::character varying, 'payment'::character varying, 'reminder'::character varying, 'promo'::character varying, 'system'::character varying]::text[])),
  title character varying NOT NULL,
  message text NOT NULL,
  is_read boolean DEFAULT false,
  data jsonb DEFAULT '{}'::jsonb,
  booking_id uuid,
  booking_code character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.passengers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid,
  passenger_id character varying,
  full_name character varying NOT NULL,
  email character varying,
  phone character varying,
  seat_number character varying,
  seat_id character varying,
  segment_id character varying,
  transit_station character varying,
  transit_arrival time without time zone,
  transit_departure time without time zone,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT passengers_pkey PRIMARY KEY (id),
  CONSTRAINT passengers_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings_kereta(id)
);
CREATE TABLE public.payment_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id character varying NOT NULL UNIQUE,
  customer_email character varying NOT NULL,
  customer_name character varying DEFAULT 'Pelanggan'::character varying,
  amount numeric NOT NULL,
  payment_method character varying NOT NULL,
  status character varying NOT NULL DEFAULT 'pending'::character varying,
  payment_url text,
  midtrans_token text,
  transaction_data jsonb,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  snap_redirect_url text,
  payment_data jsonb,
  settlement_time timestamp without time zone,
  payment_type character varying,
  transaction_id character varying,
  fare_breakdown jsonb DEFAULT '{}'::jsonb,
  booking_id uuid,
  CONSTRAINT payment_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT fk_payment_transactions_bookings FOREIGN KEY (booking_id) REFERENCES public.bookings_kereta(id)
);
CREATE TABLE public.pembayaran (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  id_pemesanan uuid,
  jumlah numeric NOT NULL,
  status character varying DEFAULT 'pending'::character varying,
  payment_type character varying,
  va_number character varying,
  transaction_id character varying,
  fraud_status character varying,
  signature_key text,
  paid_at timestamp with time zone,
  rejected_at timestamp with time zone,
  catatan text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pembayaran_pkey PRIMARY KEY (id),
  CONSTRAINT pembayaran_id_pemesanan_fkey FOREIGN KEY (id_pemesanan) REFERENCES public.pemesanan(id)
);
CREATE TABLE public.pemesanan (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  rute_id uuid,
  penumpang_id uuid,
  tanggal_pemesanan timestamp with time zone DEFAULT now(),
  kode_promo character varying,
  status character varying DEFAULT 'pending'::character varying,
  total_harga numeric NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pemesanan_pkey PRIMARY KEY (id),
  CONSTRAINT pemesanan_penumpang_id_fkey FOREIGN KEY (penumpang_id) REFERENCES public.penumpang(id)
);
CREATE TABLE public.penumpang (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nama character varying NOT NULL,
  nik character varying,
  tanggal_lahir date,
  gender character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  email character varying,
  phone character varying,
  passenger_order integer,
  booking_id uuid,
  CONSTRAINT penumpang_pkey PRIMARY KEY (id),
  CONSTRAINT penumpang_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings_kereta(id)
);
CREATE TABLE public.point_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  booking_id uuid,
  points integer NOT NULL,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['earn'::character varying, 'redeem'::character varying, 'expire'::character varying, 'bonus'::character varying, 'adjustment'::character varying]::text[])),
  description text NOT NULL,
  status character varying DEFAULT 'completed'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'completed'::character varying, 'cancelled'::character varying, 'expired'::character varying]::text[])),
  expires_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT point_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT point_transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT point_transactions_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings_kereta(id)
);
CREATE TABLE public.promotions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  description text,
  promo_code character varying NOT NULL UNIQUE,
  discount_type character varying NOT NULL,
  discount_value numeric NOT NULL,
  min_order_amount numeric DEFAULT 0,
  max_discount_amount numeric,
  start_date timestamp with time zone NOT NULL,
  end_date timestamp with time zone NOT NULL,
  usage_limit integer,
  usage_count integer DEFAULT 0,
  user_limit integer DEFAULT 1,
  is_active boolean DEFAULT true,
  applicable_to jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT promotions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.rute_kereta (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  schedule_id uuid,
  origin_station_id uuid,
  destination_station_id uuid,
  route_order integer NOT NULL,
  arrival_time time without time zone NOT NULL,
  departure_time time without time zone NOT NULL,
  duration_minutes integer NOT NULL CHECK (duration_minutes > 0),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  train_id uuid,
  station_order integer NOT NULL DEFAULT 0,
  CONSTRAINT rute_kereta_pkey PRIMARY KEY (id),
  CONSTRAINT rute_kereta_schedule_id_fkey FOREIGN KEY (schedule_id) REFERENCES public.jadwal_kereta(id),
  CONSTRAINT rute_kereta_origin_station_id_fkey FOREIGN KEY (origin_station_id) REFERENCES public.stasiun(id),
  CONSTRAINT rute_kereta_destination_station_id_fkey FOREIGN KEY (destination_station_id) REFERENCES public.stasiun(id),
  CONSTRAINT rute_kereta_train_id_fkey FOREIGN KEY (train_id) REFERENCES public.kereta(id)
);
CREATE TABLE public.seat (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  id_rute uuid,
  id_gerbong uuid,
  pemesanan_id uuid,
  kode_kursi character varying NOT NULL,
  from_stop_urutan integer,
  to_stop_urutan integer,
  status character varying DEFAULT 'available'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT seat_pkey PRIMARY KEY (id),
  CONSTRAINT seat_id_gerbong_fkey FOREIGN KEY (id_gerbong) REFERENCES public.gerbong(id),
  CONSTRAINT seat_pemesanan_id_fkey FOREIGN KEY (pemesanan_id) REFERENCES public.pemesanan(id)
);
CREATE TABLE public.stasiun (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  kode_stasiun character varying NOT NULL UNIQUE,
  nama_stasiun character varying NOT NULL,
  city character varying NOT NULL,
  type USER-DEFINED,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  tipe character varying,
  CONSTRAINT stasiun_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tickets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id character varying NOT NULL,
  ticket_number character varying NOT NULL UNIQUE,
  qr_code text,
  status character varying DEFAULT 'active'::character varying,
  passenger_name character varying,
  passenger_email character varying,
  train_name character varying,
  departure_date date,
  departure_time time without time zone,
  arrival_time time without time zone,
  origin character varying,
  destination character varying,
  seat_number character varying,
  coach_number character varying,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT tickets_pkey PRIMARY KEY (id)
);
CREATE TABLE public.train_seats (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  schedule_id uuid,
  coach_id uuid,
  seat_number character varying NOT NULL,
  from_route_id uuid,
  to_route_id uuid,
  status USER-DEFINED DEFAULT 'available'::seat_status_enum,
  booking_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  departure_route_order integer,
  arrival_route_order integer,
  CONSTRAINT train_seats_pkey PRIMARY KEY (id),
  CONSTRAINT train_seats_schedule_id_fkey FOREIGN KEY (schedule_id) REFERENCES public.jadwal_kereta(id),
  CONSTRAINT train_seats_coach_id_fkey FOREIGN KEY (coach_id) REFERENCES public.gerbong(id),
  CONSTRAINT train_seats_from_route_id_fkey FOREIGN KEY (from_route_id) REFERENCES public.rute_kereta(id),
  CONSTRAINT train_seats_to_route_id_fkey FOREIGN KEY (to_route_id) REFERENCES public.rute_kereta(id),
  CONSTRAINT train_seats_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings_kereta(id)
);
CREATE TABLE public.transit_booking_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  transit_route_id uuid NOT NULL,
  action character varying NOT NULL CHECK (action::text = ANY (ARRAY['booked'::character varying, 'modified'::character varying, 'cancelled'::character varying, 'confirmed'::character varying]::text[])),
  details jsonb DEFAULT '{}'::jsonb,
  performed_by uuid,
  performed_at timestamp with time zone DEFAULT now(),
  CONSTRAINT transit_booking_history_pkey PRIMARY KEY (id),
  CONSTRAINT transit_booking_history_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings_kereta(id),
  CONSTRAINT transit_booking_history_transit_route_id_fkey FOREIGN KEY (transit_route_id) REFERENCES public.transit_routes(id)
);
CREATE TABLE public.transit_pricing (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  transit_route_id uuid NOT NULL,
  segment_id uuid,
  day_of_week integer CHECK (day_of_week >= 0 AND day_of_week <= 6),
  time_slot_start time without time zone,
  time_slot_end time without time zone,
  price_multiplier numeric DEFAULT 1.0 CHECK (price_multiplier > 0::numeric),
  is_active boolean DEFAULT true,
  start_date date,
  end_date date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT transit_pricing_pkey PRIMARY KEY (id),
  CONSTRAINT transit_pricing_transit_route_id_fkey FOREIGN KEY (transit_route_id) REFERENCES public.transit_routes(id),
  CONSTRAINT transit_pricing_segment_id_fkey FOREIGN KEY (segment_id) REFERENCES public.transit_segments(id)
);
CREATE TABLE public.transit_routes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  route_code character varying NOT NULL UNIQUE,
  route_name character varying NOT NULL,
  description text,
  base_price numeric NOT NULL CHECK (base_price >= 0::numeric),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT transit_routes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.transit_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  transit_route_id uuid NOT NULL,
  rule_type character varying NOT NULL CHECK (rule_type::text = ANY (ARRAY['booking_window'::character varying, 'cancellation'::character varying, 'luggage'::character varying, 'transfer'::character varying, 'other'::character varying]::text[])),
  rule_name character varying NOT NULL,
  rule_description text,
  rule_value jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT transit_rules_pkey PRIMARY KEY (id),
  CONSTRAINT transit_rules_transit_route_id_fkey FOREIGN KEY (transit_route_id) REFERENCES public.transit_routes(id)
);
CREATE TABLE public.transit_seats (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  transit_segment_id uuid NOT NULL,
  seat_id uuid,
  seat_number character varying NOT NULL,
  coach_number character varying,
  passenger_name character varying,
  from_station_id uuid NOT NULL,
  to_station_id uuid NOT NULL,
  price_adjustment numeric DEFAULT 0,
  status character varying DEFAULT 'reserved'::character varying CHECK (status::text = ANY (ARRAY['reserved'::character varying, 'confirmed'::character varying, 'cancelled'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT transit_seats_pkey PRIMARY KEY (id),
  CONSTRAINT transit_seats_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings_kereta(id),
  CONSTRAINT transit_seats_transit_segment_id_fkey FOREIGN KEY (transit_segment_id) REFERENCES public.transit_segments(id),
  CONSTRAINT transit_seats_seat_id_fkey FOREIGN KEY (seat_id) REFERENCES public.train_seats(id),
  CONSTRAINT transit_seats_from_station_id_fkey FOREIGN KEY (from_station_id) REFERENCES public.stasiun(id),
  CONSTRAINT transit_seats_to_station_id_fkey FOREIGN KEY (to_station_id) REFERENCES public.stasiun(id)
);
CREATE TABLE public.transit_segments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  transit_route_id uuid NOT NULL,
  segment_order integer NOT NULL CHECK (segment_order >= 0),
  train_id uuid,
  train_schedule_id uuid,
  origin_station_id uuid NOT NULL,
  destination_station_id uuid NOT NULL,
  departure_time time without time zone NOT NULL,
  arrival_time time without time zone NOT NULL,
  duration_minutes integer NOT NULL CHECK (duration_minutes > 0),
  waiting_minutes integer DEFAULT 0 CHECK (waiting_minutes >= 0),
  price_adjustment numeric DEFAULT 0,
  available_seats integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT transit_segments_pkey PRIMARY KEY (id),
  CONSTRAINT transit_segments_origin_station_id_fkey FOREIGN KEY (origin_station_id) REFERENCES public.stasiun(id),
  CONSTRAINT transit_segments_destination_station_id_fkey FOREIGN KEY (destination_station_id) REFERENCES public.stasiun(id),
  CONSTRAINT transit_segments_transit_route_id_fkey FOREIGN KEY (transit_route_id) REFERENCES public.transit_routes(id),
  CONSTRAINT transit_segments_train_schedule_id_fkey FOREIGN KEY (train_schedule_id) REFERENCES public.jadwal_kereta(id),
  CONSTRAINT transit_segments_train_id_fkey FOREIGN KEY (train_id) REFERENCES public.kereta(id)
);
CREATE TABLE public.transit_stations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  station_id uuid NOT NULL,
  transit_route_id uuid NOT NULL,
  segment_id uuid,
  stop_order integer NOT NULL,
  is_mandatory_transit boolean DEFAULT false,
  min_waiting_minutes integer DEFAULT 15,
  max_waiting_minutes integer DEFAULT 120,
  available_for_booking boolean DEFAULT true,
  transit_fee numeric DEFAULT 0 CHECK (transit_fee >= 0::numeric),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT transit_stations_pkey PRIMARY KEY (id),
  CONSTRAINT transit_stations_station_id_fkey FOREIGN KEY (station_id) REFERENCES public.stasiun(id),
  CONSTRAINT transit_stations_transit_route_id_fkey FOREIGN KEY (transit_route_id) REFERENCES public.transit_routes(id),
  CONSTRAINT transit_stations_segment_id_fkey FOREIGN KEY (segment_id) REFERENCES public.transit_segments(id)
);
CREATE TABLE public.trip_points (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE,
  total_points integer NOT NULL DEFAULT 0,
  available_points integer NOT NULL DEFAULT 0,
  spent_points integer NOT NULL DEFAULT 0,
  level character varying DEFAULT 'bronze'::character varying,
  last_earned_at timestamp with time zone,
  next_reset_date date DEFAULT (CURRENT_DATE + '1 year'::interval),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT trip_points_pkey PRIMARY KEY (id),
  CONSTRAINT trip_points_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_promo_usage (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  promotion_id uuid,
  booking_id uuid,
  usage_date timestamp with time zone DEFAULT now(),
  discount_applied numeric NOT NULL,
  CONSTRAINT user_promo_usage_pkey PRIMARY KEY (id),
  CONSTRAINT user_promo_usage_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_promo_usage_promotion_id_fkey FOREIGN KEY (promotion_id) REFERENCES public.promotions(id)
);
CREATE TABLE public.user_promotions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  promotion_id uuid,
  usage_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_promotions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  email character varying NOT NULL UNIQUE,
  name character varying,
  phone character varying,
  role USER-DEFINED DEFAULT 'user'::role_enum,
  avatar_url text,
  date_of_birth date,
  gender character varying,
  address text,
  email_verified boolean DEFAULT false,
  phone_verified boolean DEFAULT false,
  last_login timestamp with time zone,
  is_active boolean DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
